### ISSUE TITLE
Offline install for npmbox is failing

### ISSUE THREAD

**Issue by balasivagnanam** [arei/npmbox#82]
I tried to install npmbox by boxing npmbox from a PC with internet, and then unzipped 2 times to a directory and tried to install it but I am getting error. Looks like its still trying to look for npm registry online.
I tried different solutions from the issues and comments on them before, but no luck.
Below is my log

```
C:\codes\npmboxpkg>npm install --global --cache .\.npmbox.cache --optional --cache-min 99999 --verbose --shrinkwrap false npmbox
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--global',
npm verb cli   '--cache',
npm verb cli   '.\\.npmbox.cache',
npm verb cli   '--optional',
npm verb cli   '--cache-min',
npm verb cli   '99999',
npm verb cli   '--verbose',
npm verb cli   '--shrinkwrap',
npm verb cli   'false',
npm verb cli   'npmbox' ]
npm info using npm@3.10.10
npm info using node@v7.2.1
npm verb get https://registry.npmjs.org/npmbox not expired, no request
npm verb cache add spec npmbox
npm verb addNamed "latest" is being treated as a dist-tag for npmbox
npm info addNameTag [ 'npmbox', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/npmbox not in flight; fetching
npm verb get https://registry.npmjs.org/npmbox not expired, no request
npm verb addNamed "4.2.0" is a plain semver version for npmbox
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npmbox\4.2.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npmbox\4.2.0\package\package.json written
npm verb get https://registry.npmjs.org/is not expired, no request
npm verb cache add spec is@3.1.0
npm verb addNamed "3.1.0" is a plain semver version for is
npm verb addNameVersion registry:https://registry.npmjs.org/is not in flight; fetching
npm verb get https://registry.npmjs.org/fs-extra not expired, no request
npm verb cache add spec fs-extra@1.0.0
npm verb addNamed "1.0.0" is a plain semver version for fs-extra
npm verb addNameVersion registry:https://registry.npmjs.org/fs-extra not in flight; fetching
npm verb get https://registry.npmjs.org/npm-package-arg not expired, no request
npm verb cache add spec npm-package-arg@4.2.0
npm verb addNamed "4.2.0" is a plain semver version for npm-package-arg
npm verb addNameVersion registry:https://registry.npmjs.org/npm-package-arg not in flight; fetching
npm verb get https://registry.npmjs.org/tar.gz not expired, no request
npm verb cache add spec tar.gz@1.0.2
npm verb addNamed "1.0.2" is a plain semver version for tar.gz
npm verb addNameVersion registry:https://registry.npmjs.org/tar.gz not in flight; fetching
npm verb get https://registry.npmjs.org/read-package-json not expired, no request
npm verb cache add spec read-package-json@2.0.4
npm verb addNamed "2.0.4" is a plain semver version for read-package-json
npm verb addNameVersion registry:https://registry.npmjs.org/read-package-json not in flight; fetching
npm verb get https://registry.npmjs.org/optimist not expired, no request
npm verb cache add spec optimist@0.6.1
npm verb addNamed "0.6.1" is a plain semver version for optimist
npm verb addNameVersion registry:https://registry.npmjs.org/optimist not in flight; fetching
npm verb get https://registry.npmjs.org/tmp not expired, no request
npm verb cache add spec tmp@0.0.31
npm verb addNamed "0.0.31" is a plain semver version for tmp
npm verb addNameVersion registry:https://registry.npmjs.org/tmp not in flight; fetching
npm verb get https://registry.npmjs.org/npm not expired, no request
npm verb cache add spec npm@3.10.3
npm verb addNamed "3.10.3" is a plain semver version for npm
npm verb addNameVersion registry:https://registry.npmjs.org/npm not in flight; fetching
npm verb get https://registry.npmjs.org/fs-extra not expired, no request
npm verb get https://registry.npmjs.org/is not expired, no request
npm verb get https://registry.npmjs.org/npm-package-arg not expired, no request
npm verb get https://registry.npmjs.org/tar.gz not expired, no request
npm verb get https://registry.npmjs.org/read-package-json not expired, no request
npm verb get https://registry.npmjs.org/optimist not expired, no request
npm verb get https://registry.npmjs.org/tmp not expired, no request
npm verb get https://registry.npmjs.org/npm not expired, no request
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\fs-extra\1.0.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\is\3.1.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm-package-arg\4.2.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\optimist\0.6.1\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\read-package-json\2.0.4\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tmp\0.0.31\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tar.gz\1.0.2\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\is\3.1.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm-package-arg\4.2.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\fs-extra\1.0.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tar.gz\1.0.2\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\read-package-json\2.0.4\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\optimist\0.6.1\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tmp\0.0.31\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package\package.json written
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb addBundled extract C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package.tgz
npm verb tar unpack C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package.tgz
npm verb tar unpacking to C:\Users\MUHDSH~1\AppData\Local\Temp\npm-12692-d51052c6\unpack-48239aa4
npm verb gentlyRm don't care about contents; nuking C:\Users\MUHDSH~1\AppData\Local\Temp\npm-12692-d51052c6\unpack-48239aa4
npm verb request uri https://registry.npmjs.org/graceful-fs
npm verb request no auth needed
npm info attempt registry request try #1 at 11:46:25 AM
npm verb request id 7d46d63b714940bb
npm http request GET https://registry.npmjs.org/graceful-fs
npm verb request uri https://registry.npmjs.org/jsonfile
npm verb request no auth needed
npm info attempt registry request try #1 at 11:46:25 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm verb request uri https://registry.npmjs.org/klaw
npm verb request no auth needed
npm info attempt registry request try #1 at 11:46:25 AM
npm http request GET https://registry.npmjs.org/klaw
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info attempt registry request try #2 at 11:46:35 AM
npm http request GET https://registry.npmjs.org/graceful-fs
npm info attempt registry request try #2 at 11:46:35 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm info attempt registry request try #2 at 11:46:35 AM
npm http request GET https://registry.npmjs.org/klaw
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info attempt registry request try #3 at 11:47:35 AM
npm http request GET https://registry.npmjs.org/graceful-fs
npm info attempt registry request try #3 at 11:47:35 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm info attempt registry request try #3 at 11:47:35 AM
npm http request GET https://registry.npmjs.org/klaw
npm verb stack Error: getaddrinfo ENOENT registry.npmjs.org:443
npm verb stack     at Object.exports._errnoException (util.js:1022:11)
npm verb stack     at errnoException (dns.js:33:15)
npm verb stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
npm verb cwd C:\codes\npmboxpkg
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" ".\\.npmbox.cache" "--optional" "--cache-min" "99999" "--verbose" "--shrinkwrap" "false" "npmbox"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall getaddrinfo

npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\codes\npmboxpkg\npm-debug.log
```

**Comment by arei** [comment]
I am wondering if the `--optional` switch has something to do with this.  Can you try the command over but without the `--optional` switch?

**Comment by balasivagnanam** [comment]
same

```
C:\codes\npmboxpkg>npm install --global --cache .\.npmbox.cache --cache-min 99999 --verbose --shrinkwrap false npmbox
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--global',
npm verb cli   '--cache',
npm verb cli   '.\\.npmbox.cache',
npm verb cli   '--cache-min',
npm verb cli   '99999',
npm verb cli   '--verbose',
npm verb cli   '--shrinkwrap',
npm verb cli   'false',
npm verb cli   'npmbox' ]
npm info using npm@3.10.10
npm info using node@v7.2.1
npm verb get https://registry.npmjs.org/npmbox not expired, no request
npm verb cache add spec npmbox
npm verb addNamed "latest" is being treated as a dist-tag for npmbox
npm info addNameTag [ 'npmbox', 'latest' ]
npm verb addNameTag registry:https://registry.npmjs.org/npmbox not in flight; fetching
npm verb get https://registry.npmjs.org/npmbox not expired, no request
npm verb addNamed "4.2.0" is a plain semver version for npmbox
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npmbox\4.2.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npmbox\4.2.0\package\package.json written
npm verb get https://registry.npmjs.org/is not expired, no request
npm verb cache add spec is@3.1.0
npm verb addNamed "3.1.0" is a plain semver version for is
npm verb addNameVersion registry:https://registry.npmjs.org/is not in flight; fetching
npm verb get https://registry.npmjs.org/fs-extra not expired, no request
npm verb cache add spec fs-extra@1.0.0
npm verb addNamed "1.0.0" is a plain semver version for fs-extra
npm verb addNameVersion registry:https://registry.npmjs.org/fs-extra not in flight; fetching
npm verb get https://registry.npmjs.org/npm-package-arg not expired, no request
npm verb cache add spec npm-package-arg@4.2.0
npm verb addNamed "4.2.0" is a plain semver version for npm-package-arg
npm verb addNameVersion registry:https://registry.npmjs.org/npm-package-arg not in flight; fetching
npm verb get https://registry.npmjs.org/tar.gz not expired, no request
npm verb cache add spec tar.gz@1.0.2
npm verb addNamed "1.0.2" is a plain semver version for tar.gz
npm verb addNameVersion registry:https://registry.npmjs.org/tar.gz not in flight; fetching
npm verb get https://registry.npmjs.org/optimist not expired, no request
npm verb cache add spec optimist@0.6.1
npm verb addNamed "0.6.1" is a plain semver version for optimist
npm verb addNameVersion registry:https://registry.npmjs.org/optimist not in flight; fetching
npm verb get https://registry.npmjs.org/read-package-json not expired, no request
npm verb cache add spec read-package-json@2.0.4
npm verb addNamed "2.0.4" is a plain semver version for read-package-json
npm verb addNameVersion registry:https://registry.npmjs.org/read-package-json not in flight; fetching
npm verb get https://registry.npmjs.org/tmp not expired, no request
npm verb cache add spec tmp@0.0.31
npm verb addNamed "0.0.31" is a plain semver version for tmp
npm verb addNameVersion registry:https://registry.npmjs.org/tmp not in flight; fetching
npm verb get https://registry.npmjs.org/npm not expired, no request
npm verb cache add spec npm@3.10.3
npm verb addNamed "3.10.3" is a plain semver version for npm
npm verb addNameVersion registry:https://registry.npmjs.org/npm not in flight; fetching
npm verb get https://registry.npmjs.org/is not expired, no request
npm verb get https://registry.npmjs.org/fs-extra not expired, no request
npm verb get https://registry.npmjs.org/npm-package-arg not expired, no request
npm verb get https://registry.npmjs.org/tar.gz not expired, no request
npm verb get https://registry.npmjs.org/read-package-json not expired, no request
npm verb get https://registry.npmjs.org/optimist not expired, no request
npm verb get https://registry.npmjs.org/tmp not expired, no request
npm verb get https://registry.npmjs.org/npm not expired, no request
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm-package-arg\4.2.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\fs-extra\1.0.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\is\3.1.0\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\read-package-json\2.0.4\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\optimist\0.6.1\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tmp\0.0.31\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tar.gz\1.0.2\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package\package.json not in flight; writing
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\is\3.1.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm-package-arg\4.2.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\fs-extra\1.0.0\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tmp\0.0.31\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\read-package-json\2.0.4\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\optimist\0.6.1\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\tar.gz\1.0.2\package\package.json written
npm verb afterAdd C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package\package.json written
npm verb correctMkdir C:\codes\npmboxpkg\.npmbox.cache correctMkdir not in flight; initializing
npm verb addBundled extract C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package.tgz
npm verb tar unpack C:\codes\npmboxpkg\.npmbox.cache\npm\3.10.3\package.tgz
npm verb tar unpacking to C:\Users\MUHDSH~1\AppData\Local\Temp\npm-3832-b4ad5ba7\unpack-38a9e934
npm verb gentlyRm don't care about contents; nuking C:\Users\MUHDSH~1\AppData\Local\Temp\npm-3832-b4ad5ba7\unpack-38a9e934
npm verb request uri https://registry.npmjs.org/graceful-fs
npm verb request no auth needed
npm info attempt registry request try #1 at 9:31:13 AM
npm verb request id ac5802419954196a
npm http request GET https://registry.npmjs.org/graceful-fs
npm verb request uri https://registry.npmjs.org/jsonfile
npm verb request no auth needed
npm info attempt registry request try #1 at 9:31:13 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm verb request uri https://registry.npmjs.org/klaw
npm verb request no auth needed
npm info attempt registry request try #1 at 9:31:13 AM
npm http request GET https://registry.npmjs.org/klaw
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info attempt registry request try #2 at 9:31:23 AM
npm http request GET https://registry.npmjs.org/graceful-fs
npm info attempt registry request try #2 at 9:31:23 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm info attempt registry request try #2 at 9:31:24 AM
npm http request GET https://registry.npmjs.org/klaw
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info retry will retry, error on last attempt: Error: getaddrinfo ENOENT registry.npmjs.org:443
npm info attempt registry request try #3 at 9:32:24 AM
npm http request GET https://registry.npmjs.org/graceful-fs
npm info attempt registry request try #3 at 9:32:24 AM
npm http request GET https://registry.npmjs.org/jsonfile
npm info attempt registry request try #3 at 9:32:24 AM
npm http request GET https://registry.npmjs.org/klaw
npm verb stack Error: getaddrinfo ENOENT registry.npmjs.org:443
npm verb stack     at Object.exports._errnoException (util.js:1022:11)
npm verb stack     at errnoException (dns.js:33:15)
npm verb stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
npm verb cwd C:\codes\npmboxpkg
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--cache" ".\\.npmbox.cache" "--cache-min" "99999" "--verbose" "--shrinkwrap" "false" "npmbox"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall getaddrinfo

npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent getaddrinfo ENOENT registry.npmjs.org:443
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\codes\npmboxpkg\npm-debug.log
```

**Comment by balasivagnanam** [comment]
works fine thanks. I also had a wrong directory reference.
